# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "higebu/vyos"

  # config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network :public_network, :bridge => "en0: Wi-Fi (AirPort)"

  # config.vm.synced_folder "./", "/vagrant"

  config.vm.provider "virtualbox" do |vb|
    # vb.gui = true
    vb.name = "vyos"
    # Customize the amount of memory on the VM:
    vb.memory = "1024"
    vb.customize ["modifyvm", :id, "--nic3", "intnet"]
    vb.customize ["modifyvm", :id, "--nictype3", "82540EM"]
    vb.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
  end

  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
